apiVersion: apps/v1
kind: Deployment
metadata:
  name: upworkwebapp
  namespace: upwork
  labels:
    app: upworkwebapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upworkwebapp
  template:
    metadata:
      labels:
        app: upworkwebapp
    spec:
      serviceAccountName: upworkwebappsa
      containers:
        - name: upworkwebapp
          image: docker.io/ashafqat/upworkimage:v1.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            requests:
              cpu: 300m
              memory: 512Mi
 