apiVersion: v1
kind: Service
metadata:
  name: upworkwebapp
  namespace: upwork
  labels:
    app: upworkwebapp
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: upworkwebapp